player_position=[4,9]#x,y
player_Map_name='map.xlsx'
player_move_speed=5#移动一格需要的分
player_condition="alive"#dead
player_is_admin=False#开发者模式
player_money=0
#下面是保存的数据
player_data_global={'player_position':[4,8],'player_Map_name':'map.xlsx','player_move_speed':5,
                    'player_condition':'alive','is_in_room':False,'player_is_admin':True,
                    "player_money":0}#存档读档都用这个